name: CDK Build & Deploy

on:
  push:
    branches:
      - '**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

  deploy:
    if: github.ref == 'refs/heads/15-github-action-backend-deploy' 
    needs: build
    runs-on: ubuntu-latest
    env:
      CRM_ENV: olivia

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
      
    - name: Transpile TypeScript
      run: npx tsc src/lambdas/index.ts

    - name: CDK Synth
      run: npx cdk synth

    - name: Deploy stack
      run: npx cdk deploy --require-approval never