name: CDK Build & Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

  test:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --force

      - name: Run tests
        run: npm run test

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    container: node:16
    env:
      CRM_ENV: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Transpile TypeScript
        run: npx tsc ./src/lambdas/index.ts

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Bootstrap AWS CDK
        run: npx cdk bootstrap

      - name: CDK Synth
        run: npx cdk synth

      - name: Deploy stack
        run: npx cdk deploy --require-approval never
