name: CDK Build & Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   container: node:16
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: cache independences
  #       id: cache-dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: set up JDK
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: "11"

  #     - name: Run tests
  #       run: npm run test

  deploy:
    if: github.ref == 'refs/heads/feature/github-actions'
    # for  test
    needs: build
    runs-on: ubuntu-latest
    container: node:16
    env:
      CRM_ENV: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: cache independences
      #   id: cache-dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: check docker version
        run: docker --version

      - name: Install dependencies
        run: npm ci

      # - name: Clean output directory
      #   run: rm -rf $GITHUB_WORKSPACE
      #   shell: bash

      # - name: TypeScript Build
      #   run: npx tsc

      - name: Transpile TypeScript
        run: npx tsc --build tsconfig.json
        shell: bash

      - name: check work place
        run: echo $GITHUB_WORKSPACE
        shell: bash

      - name: list files 01
        run: ls $GITHUB_WORKSPACE -al

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Bootstrap AWS CDK
        run: npx cdk bootstrap

      - name: CDK Synth
        run: npx cdk synth

      - name: Deploy stack
        run: npx cdk deploy --require-approval never
