name: CDK Build & Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

  test:
    needs: build
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Run tests
        run: npm run test

  configure:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  deploy:
    if: github.ref == 'refs/heads/feature/github-actions'
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user ${{ needs.configure.outputs.uid_gid }}
    env:
      CRM_ENV: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set_up_nodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: build
        run: npm run build
        shell: bash

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Bootstrap AWS CDK
        run: cdk bootstrap

      - name: CDK Synth
        run: cdk synth

      - name: Deploy stack
        run: cdk deploy --require-approval never
